import type { Garment, GarmentId, Moment, OutfitProposal, Season, Slot } from '../src/domain/types';

const ALL_SEASONS: readonly Season[] = ['spring', 'summer', 'autumn', 'winter'];

const DEFAULTS: Omit<Garment, 'id' | 'slot' | 'subtype'> = {
  imageOriginal: 'r2/original.jpg',
  imageCutout: null,
  colors: [],
  colorRole: 'neutral',
  pattern: 'solid',
  fabric: null,
  warmth: 2,
  formality: 3,
  fit: null,
  structured: false,
  rise: null,
  leg: null,
  hem: null,
  neckline: null,
  sleeves: null,
  shoulderBulk: false,
  waterResistant: false,
  seasons: ALL_SEASONS,
  notes: null,
};

interface GarmentSpec extends Partial<Omit<Garment, 'id' | 'slot' | 'subtype'>> {
  readonly id: string;
  readonly slot: Slot;
  readonly subtype: string;
}

function garment(spec: GarmentSpec): Garment {
  return { ...DEFAULTS, ...spec, id: spec.id as GarmentId };
}

/**
 * For a garment shape the wardrobe has none of. Adding one to `WARDROBE` would
 * move the menu counts every other test reads.
 */
export const makeGarment = garment;

/** A wardrobe with the thin spots a real one has: one wide-leg trouser, one waterproof boot. */
export const WARDROBE: readonly Garment[] = [
  garment({
    id: 'tee-white',
    slot: 'base',
    subtype: 'cotton t-shirt',
    colors: ['white'],
    fabric: 'cotton',
    warmth: 1,
    formality: 2,
    fit: 'fitted',
    neckline: 'crew',
    sleeves: 'short',
    hem: 'at_waist',
    seasons: ['spring', 'summer', 'autumn'],
  }),
  garment({
    id: 'tank-gray',
    slot: 'base',
    subtype: 'tank top',
    colors: ['gray'],
    fabric: 'cotton',
    warmth: 0,
    formality: 1,
    fit: 'tight',
    neckline: 'none',
    sleeves: 'none',
    hem: 'at_waist',
    seasons: ['summer'],
  }),
  garment({
    id: 'henley-navy',
    slot: 'base',
    subtype: 'henley',
    colors: ['navy'],
    fabric: 'cotton',
    warmth: 2,
    formality: 3,
    fit: 'regular',
    neckline: 'v',
    sleeves: 'long',
    hem: 'at_waist',
    seasons: ['spring', 'autumn', 'winter'],
  }),
  garment({
    id: 'tee-merino-white',
    slot: 'base',
    subtype: 'merino crew tee',
    colors: ['white'],
    fabric: 'wool',
    warmth: 2,
    formality: 4,
    fit: 'regular',
    structured: true,
    neckline: 'crew',
    sleeves: 'short',
    hem: 'at_waist',
  }),

  garment({
    id: 'oxford-blue',
    slot: 'top',
    subtype: 'oxford shirt',
    colors: ['light blue'],
    fabric: 'cotton',
    warmth: 2,
    formality: 4,
    fit: 'regular',
    structured: true,
    neckline: 'open',
    sleeves: 'long',
    hem: 'past_waist',
  }),
  garment({
    id: 'polo-navy',
    slot: 'top',
    subtype: 'polo shirt',
    colors: ['navy'],
    fabric: 'cotton',
    warmth: 2,
    formality: 3,
    fit: 'regular',
    neckline: 'crew',
    sleeves: 'short',
    hem: 'at_waist',
    seasons: ['spring', 'summer', 'autumn'],
  }),
  garment({
    id: 'flannel-check',
    slot: 'top',
    subtype: 'flannel shirt',
    colors: ['red', 'navy'],
    fabric: 'cotton',
    pattern: 'check',
    warmth: 3,
    formality: 2,
    fit: 'relaxed',
    neckline: 'open',
    sleeves: 'long',
    hem: 'hip',
    seasons: ['autumn', 'winter'],
  }),
  garment({
    id: 'linen-shirt-beige',
    slot: 'top',
    subtype: 'linen shirt',
    colors: ['beige'],
    fabric: 'linen',
    warmth: 1,
    formality: 3,
    fit: 'relaxed',
    neckline: 'open',
    sleeves: 'long',
    hem: 'past_waist',
    seasons: ['spring', 'summer'],
  }),

  garment({
    id: 'blazer-navy',
    slot: 'mid',
    subtype: 'unstructured blazer',
    colors: ['navy'],
    fabric: 'wool',
    warmth: 3,
    formality: 5,
    fit: 'fitted',
    structured: true,
    neckline: 'open',
    sleeves: 'long',
    hem: 'hip',
  }),
  garment({
    id: 'cardigan-gray',
    slot: 'mid',
    subtype: 'cardigan',
    colors: ['gray'],
    fabric: 'wool',
    warmth: 3,
    formality: 3,
    fit: 'regular',
    neckline: 'v',
    sleeves: 'long',
    hem: 'at_waist',
    seasons: ['spring', 'autumn', 'winter'],
  }),
  garment({
    id: 'knit-cream-heavy',
    slot: 'mid',
    subtype: 'heavy knit sweater',
    colors: ['cream'],
    fabric: 'wool',
    warmth: 4,
    formality: 2,
    fit: 'oversized',
    shoulderBulk: true,
    neckline: 'crew',
    sleeves: 'long',
    hem: 'hip',
    seasons: ['winter'],
  }),

  garment({
    id: 'rain-jacket-black',
    slot: 'outer',
    subtype: 'rain shell',
    colors: ['black'],
    fabric: 'synthetic',
    warmth: 2,
    formality: 2,
    fit: 'regular',
    waterResistant: true,
    neckline: 'high',
    sleeves: 'long',
    hem: 'hip',
    seasons: ['spring', 'autumn', 'winter'],
  }),
  garment({
    id: 'wool-coat-camel',
    slot: 'outer',
    subtype: 'wool overcoat',
    colors: ['camel'],
    fabric: 'wool',
    warmth: 5,
    formality: 4,
    fit: 'regular',
    structured: true,
    neckline: 'open',
    sleeves: 'long',
    hem: 'below_hip',
    seasons: ['autumn', 'winter'],
  }),
  garment({
    id: 'puffer-navy',
    slot: 'outer',
    subtype: 'puffer jacket',
    colors: ['navy'],
    fabric: 'synthetic',
    warmth: 5,
    formality: 2,
    fit: 'relaxed',
    shoulderBulk: true,
    waterResistant: true,
    neckline: 'high',
    sleeves: 'long',
    hem: 'hip',
    seasons: ['winter'],
  }),
  garment({
    id: 'gilet-olive',
    slot: 'outer',
    subtype: 'quilted gilet',
    colors: ['olive'],
    fabric: 'synthetic',
    warmth: 2,
    formality: 2,
    fit: 'regular',
    neckline: 'high',
    sleeves: 'none',
    hem: 'at_waist',
    seasons: ['spring', 'autumn'],
  }),
  garment({
    id: 'trench-navy',
    slot: 'outer',
    subtype: 'trench coat',
    colors: ['navy'],
    fabric: 'cotton',
    warmth: 3,
    formality: 4,
    fit: 'regular',
    structured: true,
    waterResistant: true,
    neckline: 'open',
    sleeves: 'long',
    hem: 'below_hip',
    seasons: ['spring', 'autumn', 'winter'],
  }),

  garment({
    id: 'jeans-indigo',
    slot: 'bottom',
    subtype: 'jeans',
    colors: ['indigo'],
    fabric: 'denim',
    warmth: 2,
    formality: 2,
    fit: 'regular',
    rise: 'mid',
    leg: 'straight',
  }),
  garment({
    id: 'jeans-black-skinny',
    slot: 'bottom',
    subtype: 'skinny jeans',
    colors: ['black'],
    fabric: 'denim',
    warmth: 2,
    formality: 3,
    fit: 'tight',
    rise: 'mid',
    leg: 'skinny',
  }),
  garment({
    id: 'chinos-stone',
    slot: 'bottom',
    subtype: 'chinos',
    colors: ['sand'],
    fabric: 'cotton',
    warmth: 2,
    formality: 3,
    fit: 'regular',
    rise: 'mid',
    leg: 'tapered',
    seasons: ['spring', 'summer', 'autumn'],
  }),
  garment({
    id: 'trousers-wool-charcoal',
    slot: 'bottom',
    subtype: 'wool trousers',
    colors: ['charcoal'],
    fabric: 'wool',
    warmth: 3,
    formality: 5,
    fit: 'regular',
    rise: 'high',
    leg: 'wide',
    seasons: ['autumn', 'winter'],
  }),
  garment({
    id: 'shorts-khaki',
    slot: 'bottom',
    subtype: 'chino shorts',
    colors: ['khaki'],
    fabric: 'cotton',
    warmth: 0,
    formality: 2,
    fit: 'regular',
    rise: 'mid',
    leg: 'straight',
    seasons: ['summer'],
  }),
  garment({
    id: 'trousers-linen-white',
    slot: 'bottom',
    subtype: 'linen trousers',
    colors: ['white'],
    fabric: 'linen',
    warmth: 1,
    formality: 4,
    fit: 'relaxed',
    rise: 'high',
    leg: 'wide',
    seasons: ['spring', 'summer'],
  }),

  garment({
    id: 'sneakers-white',
    slot: 'shoes',
    subtype: 'leather sneakers',
    colors: ['white'],
    fabric: 'leather',
    warmth: 1,
    formality: 2,
  }),
  garment({
    id: 'chelsea-boots-black',
    slot: 'shoes',
    subtype: 'chelsea boots',
    colors: ['black'],
    fabric: 'leather',
    warmth: 2,
    formality: 4,
    waterResistant: true,
    seasons: ['spring', 'autumn', 'winter'],
  }),
  garment({
    id: 'loafers-brown',
    slot: 'shoes',
    subtype: 'penny loafers',
    colors: ['brown'],
    fabric: 'leather',
    warmth: 1,
    formality: 4,
  }),
  garment({
    id: 'oxfords-black',
    slot: 'shoes',
    subtype: 'oxford shoes',
    colors: ['black'],
    fabric: 'leather',
    warmth: 1,
    formality: 5,
  }),

  garment({
    id: 'belt-brown',
    slot: 'accessory',
    subtype: 'leather belt',
    colors: ['brown'],
    fabric: 'leather',
    warmth: 0,
    formality: 4,
  }),
  garment({
    id: 'scarf-wool-charcoal',
    slot: 'accessory',
    subtype: 'wool scarf',
    colors: ['charcoal'],
    fabric: 'wool',
    warmth: 1,
    formality: 3,
    seasons: ['autumn', 'winter'],
  }),
  garment({
    id: 'cap-navy',
    slot: 'accessory',
    subtype: 'baseball cap',
    colors: ['navy'],
    fabric: 'cotton',
    warmth: 0,
    formality: 1,
  }),
];

export function garmentById(id: string): Garment {
  const found = WARDROBE.find((g) => g.id === id);
  if (found === undefined) throw new Error(`no fixture garment ${id}`);
  return found;
}

/** Autumn in the southern hemisphere. */
export const AUTUMN_DAY = new Date('2026-05-12T09:00:00Z');
export const WINTER_DAY = new Date('2026-07-15T09:00:00Z');
export const SUMMER_DAY = new Date('2026-01-20T09:00:00Z');

export function daysBefore(date: Date, days: number): Date {
  return new Date(date.getTime() - days * 86_400_000);
}

export const MILD_ERRANDS: Moment = {
  tempC: 16,
  feelsLikeC: 15,
  precipProbability: 0.1,
  windKph: 10,
  event: 'errands',
  timeOfDay: 'morning',
  hoursOutdoors: 2,
  date: AUTUMN_DAY,
};

/** Hot enough that a tank on its own sits inside the warmth band. */
export const HOT_ERRANDS: Moment = {
  tempC: 29,
  feelsLikeC: 27,
  precipProbability: 0.05,
  windKph: 8,
  event: 'errands',
  timeOfDay: 'afternoon',
  hoursOutdoors: 2,
  date: SUMMER_DAY,
};

export const COOL_FORMAL: Moment = {
  tempC: 9,
  feelsLikeC: 8,
  precipProbability: 0.05,
  windKph: 10,
  event: 'formal',
  timeOfDay: 'evening',
  hoursOutdoors: 1,
  date: WINTER_DAY,
};

export const WET_FORMAL: Moment = {
  tempC: 9,
  feelsLikeC: 8,
  precipProbability: 0.8,
  windKph: 10,
  event: 'formal',
  timeOfDay: 'evening',
  hoursOutdoors: 3,
  date: WINTER_DAY,
};

export function proposal(over: Partial<OutfitProposal>): OutfitProposal {
  return {
    base: 'tee-white',
    bottom: 'jeans-indigo',
    shoes: 'sneakers-white',
    rationale: 'A plain layered look for a mild errand run.',
    citedRules: ['rect-01'],
    ...over,
  };
}
